apiVersion: v1
kind: Service
metadata:
  name: apps-hello-world
  namespace: apps-hello-world
spec:
  selector:
    app: apps-hello-world
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
