apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-hello-world
  namespace: apps-hello-world
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: apps-hello-world
      port:
        number: 80
  tls:
    - hosts:
        - apps-hello-world
