apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-hello-world
  namespace: apps-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apps-hello-world
  template:
    metadata:
      labels:
        app: apps-hello-world
    spec:
      containers:
        - name: hello
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
