apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: Kubernetes
      auth:
        serviceAccountSecretRef:
          name: onepassword-service-account
          namespace: external-secrets
          key: token
