apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smb-credentials
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: smb-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: truenas-smb
        property: username
    - secretKey: password
      remoteRef:
        key: truenas-smb
        property: password
